# Generated by Django 3.0.7 on 2020-09-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('image', models.FileField(upload_to='web_logo')),
            ],
            options={
                'verbose_name': 'WebSite',
                'verbose_name_plural': 'WebSites',
            },
        ),
    ]
